export const PROMPT = `
You are an expert data extraction person specializing in parsing apartment rental posts, often from Israeli social media groups. Your job is to parse information from unstructured text (which may be in English, Hebrew, or a mix) into a structured JSON object.

You are given a JSON schema. 

THINK
	* Break the given text into sentences, and extract what you can into the relevant fields in the JSON schema you got. 
	*  The "notes" field should capture important details that don't fit elsewhere, like information on other fees ("arnona", "vaad bayit"), or if there's no realtor fee ("lelo tivuch").
	* Do NOT guess nor deduct anything. Only produce output that is already written in the given text. In case you don't know, go for null.
	*  Recognize common Hebrew terms like: "שותפים" (roommates), "דירה" (apartment), "חדרים" (rooms), "קומה" (floor), "מעלית" (elevator), "מרפסת" (balcony), "מזגן" (air conditioner), "חניה" (parking), "משופצת" (renovated). 
	* Pay attention to slang, or typos.
	* Before answering back, go over what you are going to produce, and fix any mistakes: typos, empty strings that should be null, note that the answer must be only in English.
	* Before answering back, go over what you are going to produce and make sure you did not add anything not in the original text!
`;

export const JERUSALEM_NEIGHBORHOODS = [
  "אבו תור - Abu Tor",
  "אט-טור - At-Tur",
  "ארמון הנציב (תלפיות מזרח) - Armon Hanatziv (East Talpiot)",
  "ארנונה (תלפיות הישנה) - Arnona (Old Talpiot)",
  "אר-ראם - Ar-Ram",
  "עטרות - Atarot",
  "באב א-זהרה - Bab a-Zahara",
  "בקעה (גאולים) - Baka (Geulim)",
  "בתי מונקאטש - Batei Munkacs",
  "בתי סיידוף - Batei Saidoff",
  "בתי אונגרין - Batei Ungarin",
  "בית הכרם - Beit HaKerem",
  "בית חנינא - Beit Hanina",
  "בית צפאפא - Beit Safafa",
  "בית וגן - Bayit VeGan",
  "בית ישראל - Beit Yisrael",
  "הבוכרים - Bukharim",
  "בית אורות - Beit Orot",
  "עץ חיים - Etz Chaim",
  "עזרת תורה - Ezrat Torah",
  "עזרת ישראל - Ezrat Yisrael",
  "הגבעה הצרפתית (גבעת שפירא) - French Hill (Givat Shapira)",
  "המושבה הגרמנית - German Colony",
  "גאולה - Geula",
  "גילה - Gilo",
  "גבעת המטוס - Givat HaMatos",
  "גבעת משואה - Givat Masua",
  "גבעת מרדכי - Givat Mordechai",
  "גבעת אורנים - Givat Oranim",
  "גבעת רם - Givat Ram",
  "גבעת הורדים - Givat HaVradim",
  "גבעת שאול - Givat Shaul",
  "המושבה היוונית - Greek Colony",
  "הר חומה - Har Homa",
  "הר נוף - Har Nof",
  "עיר דוד - City of David",
  "הר הצופים - Mount Scopus",
  "הר הזיתים - Mount of Olives",
  "הר ציון - Mount Zion",
  "הרובע הארמני - Armenian Quarter",
  "הרובע הנוצרי - Christian Quarter",
  "הרובע היהודי - Jewish Quarter",
  "הרובע המוסלמי - Muslim Quarter",
  "הרובע המרוקאי - Moroccan Quarter",
  "המוריסטן - The Muristan",
  "הקרדו - The Cardo",
  "ואדי ג׳וז - Wadi al-Joz",
  "ימין משה - Yemin Moshe",
  "קטמון - Katamon",
  "כרם אברהם - Kerem Avraham",
  "קריית בעלז - Kiryat Belz",
  "קריית מטרסדורף - Kiryat Mattersdorf",
  "קריית מנחם - Kiryat Menachem",
  "קריית משה - Kiryat Moshe",
  "קריית סאנץ - Kiryat Sanz",
  "קריית שמואל - Kiryat Shmuel",
  "קריית אונסדורף - Kiryat Unsdorf",
  "קריית וולפסון - Kiryat Wolfson",
  "קריית יובל - Kiryat HaYovel",
  "ליפתא - Lifta",
  "מעלות דפנה - Ma'alot Dafna",
  "מחנה יהודה - Mahane Yehuda",
  "מחנה ישראל - Mahane Israel",
  "מאה שערים - Mea Shearim",
  "מזכרת משה - Mazkeret Moshe",
  "ממילא - Mamilla",
  "מקור ברוך - Mekor Baruch",
  "מקור חיים - Makor Chaim",
  "מלחה - Malha",
  "משכנות שאננים - Mishkenot Sha'ananim",
  "מוסררה (מורשה) - Musrara (Morasha)",
  "מרכז העיר - City Center",
  "נחלת אחים - Nahalat Ahim",
  "נחלת שבעה - Nahalat Shiv'a",
  "נחלאות - Nachlaot",
  "ניות - Nayot",
  "נווה גרנות - Neve Granot",
  "נווה יעקב - Neve Yaakov",
  "נווה שאנן - Neve Sha'anan",
  "נוף ציון - Nof Zion",
  "אוהל שלמה - Ohel Shlomo",
  "פת - Pat",
  "פסגת זאב - Pisgat Ze'ev",
  "רמת בית הכרם - Ramat Beit HaKerem",
  "רמת דניה - Ramat Denya",
  "רמת אשכול - Ramat Eshkol",
  "רמת פולין - Ramot Polin",
  "רמת שלמה - Ramat Shlomo",
  "רמות - Ramot",
  "ראס אל-עמוד - Ras al-Amud",
  "רסקו - Rassco",
  "רחביה - Rehavia",
  "רוממה - Romema",
  "המתחם הרוסי - Russian Compound",
  "סן סימון - San Simon",
  "סנהדריה - Sanhedria",
  "סנהדריה המורחבת - Sanhedria Hamurchevet",
  "שערי חסד - Sha'arei Hesed",
  "שערי צדק - Sha'arei Tzedek",
  "שערי ירושלים - Sha'arei Yerushalayim",
  "שייח׳ באדר - Sheikh Badr",
  "שייח׳ ג׳ראח - Sheikh Jarrah",
  "שיכון חב״ד - Shikun Chabad",
  "שמואל הנביא - Shmuel HaNavi",
  "שועפט - Shuafat",
  "סילואן - Silwan",
  "צור באחר - Sur Baher",
  "תלפיות - Talpiot",
  "תל ארזה - Tel Arza",
  "אום ליסון - Umm Leisun",
  "אום טובה - Umm Tuba",
  "יפה נוף - Yefe Nof",
  "זכרון משה - Zichron Moshe",
];
